services:
  stable-diffusion:
    image: ${IMAGE}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    # secrets:
    #   - gradio_auth
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - UID=${UID}
      # - GID=${GID}
      # - DIR_GRADIO_AUTH=/run/secrets/gradio_auth
    volumes:
      - ${WORKSPACE_DIR}/stable-diffusion-webui:/home/user/workspace
      # - ${DIR_OUT}:/home/user/stable-diffusion-webui/outputs
      # - ${DIR_STYLES}:/home/user/stable-diffusion-webui/styles
      # - ${DIR_EXTENSIONS}:/home/user/stable-diffusion-webui/extensions
      # - ${DIR_UI_CONFIG}:/home/user/stable-diffusion-webui/settings/ui-config-user.json
      # # - ${DIR_UI_SETTINGS}:/home/user/stable-diffusion-webui/settings/config-user.json
      # - ${DIR_WEBUI_SETTINGS}:/home/user/stable-diffusion-webui/settings/webui-user.sh
      # # SET FOR DEBUG PURPOSE
      # # - ./scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
    ports:
      - ${WEBUI_PORT}:7860
    entrypoint: ${ENTRYPOINT}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
# secrets:
#   gradio_auth:
#     file: ${DIR_GRADIO_AUTH}