version: "3"
services:
  stable-diffusion:
    image: ${IMAGE_VERSION}
    restart: unless-stopped
    container_name: ${CONTAINER_NAME}
    secrets:
      - gradio_auth
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=${UID}
      - GID=${GID}
      - DIR_GRADIO_AUTH=/run/secrets/gradio_auth
    volumes:
      - ${DIR_MODEL}:/home/user/stable-diffusion-webui/models/Stable-diffusion
      - ${DIR_OUT}:/home/user/stable-diffusion-webui/outputs
      - ${DIR_STYLES}:/home/user/stable-diffusion-webui/styles
      - ${DIR_EXTENSIONS}:/home/user/stable-diffusion-webui/models/extensions
      - ${DIR_VAE}:/home/user/stable-diffusion-webui/models/VAE
      - ${DIR_UI_CONFIG}:/home/user/stable-diffusion-webui/ui-config-user.json
      - ${DIR_UI_SETTINGS}:/home/user/stable-diffusion-webui/config-user.json
      - ${DIR_WEBUI_SETTINGS}:/home/user/stable-diffusion-webui/webui-user.sh
      # SET FOR DEBUG PURPOSE
      # - <YOUR_DIRECTORY_TO_entrypoint-debug.sh>:/usr/local/bin/entrypoint.sh
    ports:
      - ${WEBUI_PORT}:7860
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
secrets:
  gradio_auth:
    file: ./secrets/gradio_auth.txt